const ERROR_CODES = {
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  SERVER_ERROR: "SERVER_ERROR",
  ID_NOT_VALID: "ID_NOT_VALID",
  ERROR: "ERROR",
  TASK_MAX_SIZE_ERR_100: "TASK_MAX_SIZE_ERR_100",
  TASK_NOT_VALID: "TASK_NOT_VALID",
  MAX_RATE_LIMIT: "MAX_RATE_LIMIT",
  REGISTER_ERROR: "REGISTER_ERROR",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
  UNATUHTORIZED: "UNATUHTORIZED",
};

export default ERROR_CODES;
